services:
  api:
    build: .
    container_name: api-container
    restart: always
    ports:
      - "6000:6000"
    volumes:
      - .:/api
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    networks:
      - api_db_network

  db:
    image: postgres
    container_name: db
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - api_db_network
      - db_management_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db_management_network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  api_db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  db_management_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24



