services:
  api:
    build: .
    container_name: api-container
    restart: always
    ports:
      - "6000:6000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: db
      DATABASE_USER: scd_student
      DATABASE_PASSWORD: tema2_scd
      DATABASE_NAME: scd_db
      DATABASE_PORT: 5432
    networks:
      - tema2_network

  db:
    image: postgres
    container_name: db
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: scd_student
      POSTGRES_PASSWORD: tema2_scd
      POSTGRES_DB: scd_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tema2_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tema2.com
      PGADMIN_DEFAULT_PASSWORD: tema2_admin
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - tema2_network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  tema2_network:
    driver: bridge



