services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: scd_student
      POSTGRES_PASSWORD: tema2_scd
      POSTGRES_DB: scd_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tema2.com
      PGADMIN_DEFAULT_PASSWORD: tema2_admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:



